// This is a placeholder file for Firebase options
// In a real application, this would be auto-generated by the Firebase CLI
// For this mock implementation, we'll define a simple structure

class FirebaseOptions {
  final String apiKey;
  final String appId;
  final String messagingSenderId;
  final String projectId;
  
  FirebaseOptions({
    required this.apiKey,
    required this.appId,
    required this.messagingSenderId,
    required this.projectId,
  });
  
  // Default platform-specific Firebase options
  static FirebaseOptions get currentPlatform {
    return FirebaseOptions(
      apiKey: 'mock-api-key',
      appId: 'mock-app-id',
      messagingSenderId: 'mock-sender-id',
      projectId: 'sman1-app',
    );
  }
}